services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    networks:
      - kennz_net
    volumes:
      - ./prometheus:/etc/prometheus/
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.1
    container_name: grafana
    networks:
      - kennz_net
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_SECURITY_ADMIN_PASSWORD=admin
networks:
  kennz_net:
    name: kennz_net
    external: true