global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'quarkus'
    metrics_path: '/q/metrics'
    scheme: https
    # accept self-signed certs
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['http2kafka:8443']